services:
  blueledger-mongo-dev-rs:
    image: mongo:8.0.13-noble
    container_name: blueledger-mongo-dev-rs
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - 27030:27017
    volumes:
      - ./data/db:/data/db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
