export const NOTIFICATION_TYPES = {
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  ADDED_TO_EXPENSE: 'ADDED_TO_EXPENSE',
  GROUP_INVITE: 'GROUP_INVITE',
} as const;

export const NOTIFICATION_TYPE_VALUES = [
  NOTIFICATION_TYPES.FRIEND_REQUEST,
  NOTIFICATION_TYPES.ADDED_TO_EXPENSE,
  NOTIFICATION_TYPES.GROUP_INVITE,
] as const;

export type NotificationType = (typeof NOTIFICATION_TYPE_VALUES)[number];
